# 1) Create Users (Registration)

### Create User: kienboec
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}

### Create User: altenhof
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}

### Create User: admin
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "admin",
  "Password": "istrator"
}

### Should fail - User already exists
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}

### Should fail - User already exists
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "different"
}


### 2) Login Users

### Login User: kienboec
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}

### Login User: altenhof
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}

### Login User: admin
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "admin",
  "Password": "istrator"
}

### Should fail - Login failed
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "different"
}
